# The baseURL will be replaced by the build script
baseURL = "https://redis.io"
title = "Docs"

timeout="75"
refLinksErrorLevel = "WARNING"
enableRobotsTXT = true
enableGitInfo = true
enableEmoji = true

contentDir = "content/"

# ignoreErrors = ["error-remote-getcsv"]

[related]
[[related.indices]]
  name = 'group'
  weight = 1
  includeNewer = true

# Highlighting config
pygmentsCodeFences = false
pygmentsUseClasses = false
# Use the new Chroma Go highlighter in Hugo.
pygmentsUseClassic = false

# Configure how URLs look like per section.
[permalinks]
blog = "/:section/:year/:month/:day/:slug/"

## Configuration for BlackFriday markdown parser: https://github.com/russross/blackfriday
[blackfriday]
plainIDAnchors = true
hrefTargetBlank = true
angledQuotes = false
latexDashes = true

# Image processing configuration.
[imaging]
resampleFilter = "CatmullRom"
quality = 75
anchor = "smart"

[params]
tagManagerId = "GTM-TKZ6J9R"
gitHubRepo = "https://github.com/redis/docs"

# Display and sort order for client examples
clientsExamples = ["Python", "Node.js", "ioredis", "Java-Sync", "Lettuce-Sync", "Java-Async", "Java-Reactive", "Go", "C", "C#-Sync", "C#-Async", "RedisVL", "PHP", "Rust-Sync", "Rust-Async"]
searchService = "/convai/api/search-service"
ratingsService = "/docusight/api/rate/docs"

# RDI params
rdi_rlec_min_version = "6.2.18"
rdi_redis_gears_version = "1.2.6"
rdi_debezium_server_version = "2.3.0.Final"
rdi_db_types = "cassandra|mysql|oracle|postgresql|sqlserver"
rdi_cli_latest = "latest"
rdi_current_version = "1.16.1"


[params.clientsConfig]
# mappingClientId maps to keys in data/command-api-mapping.json for method signatures
"Python"={quickstartSlug="redis-py", langId="python", clientId="redis-py", clientName="redis-py", mappingClientId="redis_py"}
"Node.js"={quickstartSlug="nodejs", langId="javascript", clientId="node-redis", clientName="node-redis", mappingClientId="node_redis"}
"ioredis"={quickstartSlug="ioredis", langId="javascript", clientId="ioredis", clientName="ioredis", mappingClientId="ioredis"}
"Java-Sync"={quickstartSlug="jedis", langId="java", clientId="jedis", clientName="Jedis", mappingClientId="jedis"}
"Lettuce-Sync"={quickstartSlug="lettuce", langId="java", clientId="lettuce", clientName="Lettuce", mappingClientId="lettuce_sync"}
"Java-Async"={quickstartSlug="lettuce", langId="java", clientId="lettuce", clientName="Lettuce", mappingClientId="lettuce_async"}
"Java-Reactive"={quickstartSlug="lettuce", langId="java", clientId="lettuce", clientName="Lettuce", mappingClientId="lettuce_reactive"}
"Go"={quickstartSlug="go", langId="go", clientId="go-redis", clientName="go-redis", mappingClientId="go-redis"}
"C"={quickstartSlug="hiredis", langId="c", clientId="hiredis", clientName="hiredis", mappingClientId=""}
"C#-Sync"={quickstartSlug="dotnet", langId="csharp", clientId="stackexchange-redis", clientName="StackExchange.Redis", mappingClientId="nredisstack_sync"}
"C#-Async"={quickstartSlug="dotnet", langId="csharp", clientId="stackexchange-redis", clientName="StackExchange.Redis", mappingClientId="nredisstack_async"}
"RedisVL"={quickstartSlug="redis-vl", langId="python", clientId="redis-vl", clientName="RedisVL", mappingClientId="redis_vl"}
"PHP"={quickstartSlug="php", langId="php", clientId="predis", clientName="Predis", mappingClientId="php"}
"Rust-Sync"={quickstartSlug="rust", langId="rust", clientId="redis-rs", clientName="redis-rs", mappingClientId="redis_rs_sync"}
"Rust-Async"={quickstartSlug="rust", langId="rust", clientId="redis-rs", clientName="redis-rs", mappingClientId="redis_rs_async"}

# Mount directories for duplicate content
[module]
[[module.mounts]]
  source = "content"
  target = "content"
[[module.mounts]]
  source = "content/operate/rs/databases/active-active/develop"
  target = "content/operate/rc/databases/active-active/develop"
  excludeFiles = ["_index.md"]

# Markup
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      typographer = false
  [markup.highlight]
      # See a complete list of available styles at https://xyproto.github.io/splash/docs/all.html
      # style = "github-dark"
      noClasses = "false"
      # Uncomment if you want your chosen highlight style used for code blocks without a specified language
      # guessSyntax = "true"

# Everything below this are Site Params

# Add markdown output
[outputFormats]
  [outputFormats.markdown]
    name = "markdown"
    baseName = "index.html"
    mediaType = "text/markdown"
    isPlainText = true

# Comment out if you don't want the "print entire section" link enabled.
[outputs]
section = ["HTML", "RSS", "Markdown"] # print
page = ["HTML", "Markdown"]